### ISSUE TITLE
q4, geometry, hint1, feedback box to wrong answer too big on SE

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#101]
second little question in first hint
![img_0098](https://user-images.githubusercontent.com/42607536/45159673-58c61500-b1df-11e8-8fa8-9a31486564c8.PNG)

**Comment by rih28** [comment]
Check in a few days

**Comment by ero24** [comment]
looks great now:
![img_90502cfd37d7-1](https://user-images.githubusercontent.com/42607536/45368175-e5574580-b5da-11e8-87c9-bd1bd3f9534e.jpeg)
