### ISSUE TITLE
Q2, Probability, sixth hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#102]
"Mary rolls a dice..."
After I chose 6/4 or 120, there's a typo in the explanation.
![img_5097](https://user-images.githubusercontent.com/42607534/45159500-cfaede00-b1de-11e8-90eb-5e27fc325da4.PNG)

**Comment by rih28** [comment]
Check in a few days

**Comment by yw666666** [comment]
fixed
