### ISSUE TITLE
Q15 in Probability, second hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#106]
Lizzy rolls a dice
"2+3=4"
![img_5103](https://user-images.githubusercontent.com/42607534/45171122-7a33fa80-b1f9-11e8-98b6-559ff9387c15.PNG)

**Comment by ero24** [comment]
mathematically correct now:
![img_0108](https://user-images.githubusercontent.com/42607536/45289108-494b1280-b4e4-11e8-936a-454977eac407.PNG)
