### ISSUE TITLE
Q11, Number, first hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#107]
"which of the following pure and mixed surds...10 root 3"
missing a space in exactvalues
![img_a1a1c39b5e7d-1](https://user-images.githubusercontent.com/42607534/45208747-43a2c200-b283-11e8-9c07-f9e772dc96f3.jpeg)

**Comment by ero24** [comment]
looks great now:
![img_0107](https://user-images.githubusercontent.com/42607536/45288968-e3f72180-b4e3-11e8-87df-88de8579e8c9.PNG)
