### ISSUE TITLE
Q14 Number, first hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#109]
"what is the next number in the sequence 1 1  2 3 5.."
there's a missing space in striaghtforward
![img_5112](https://user-images.githubusercontent.com/42607534/45209651-6c2bbb80-b285-11e8-8a20-086a40ed2548.PNG)

**Comment by rih28** [comment]
This is fine.

**Comment by yw666666** [comment]
omg yes it's fine, I didn't know why I said that...sorry
