### ISSUE TITLE
Qn4 in Number 

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#11]
In the second hint for Qn4 in Number, "33^1/3 root3" appeared out of nowhere. What does this mean?

**Comment by yw666666** [comment]
Qn6 "Evaluate 8^2/3" in Number
second hint, "22^1/3 cube root 2" also appeared.

**Comment by rih28** [comment]
Q4 "Evaluate 4^(3/2)" in Number

**Comment by rih28** [comment]
I think this has been resolved, will check when new version of the app is out.

**Comment by yw666666** [comment]
worked fine on both qns on 6s plus and SE
