### ISSUE TITLE
Q20, Number, third hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#110]
number machines question
a minor typo, it should be a full stop instead of question mark
![img_cf97f48d868a-1](https://user-images.githubusercontent.com/42607534/45210332-325bb480-b287-11e8-8126-f8bad3e62e23.jpeg)

**Comment by ero24** [comment]
just perfect:

![img_0106](https://user-images.githubusercontent.com/42607536/45288528-cffef000-b4e2-11e8-95cf-4c76c52bb161.PNG)
