### ISSUE TITLE
Q21, Number, third hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#111]
Sam catching a train
"there a 60 minutes"
![img_ed13516af949-1](https://user-images.githubusercontent.com/42607534/45210639-0c82df80-b288-11e8-9054-995b2a5d31d5.jpeg)

**Comment by ero24** [comment]
looks fab:

![img_0105](https://user-images.githubusercontent.com/42607536/45288445-98904380-b4e2-11e8-8b67-49425813c3ce.PNG)
