### ISSUE TITLE
q3, Stats, hint3, first little question, missing space

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#113]
I think it would be more consistent if there was a space after 600
![img_0112](https://user-images.githubusercontent.com/42607536/45290610-f2dfd300-b4e7-11e8-989d-fbcec2cdd3ff.PNG)

**Comment by rih28** [comment]
Check with v1.7.1

**Comment by ero24** [comment]
looks cool now:

![img_33a61f6bdb52-1](https://user-images.githubusercontent.com/42607536/45478122-1fd7f400-b73b-11e8-9fa2-498aa6f35dee.jpeg)
