### ISSUE TITLE
Q1 in algebra, fourth hint, third little question, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#114]
in our sequence
![img_5213](https://user-images.githubusercontent.com/42607534/45290924-a943b800-b4e8-11e8-863a-73ab40bfb646.PNG)

**Comment by rih28** [comment]
Check with v1.7.1

**Comment by ero24** [comment]
looks great now
![img_13b3caf90084-1](https://user-images.githubusercontent.com/42607536/45476596-3d0ac380-b737-11e8-93ea-661716d84672.jpeg)
