### ISSUE TITLE
Q1 algebra, fifth hint typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#115]
we know the nthe term
![img_5214](https://user-images.githubusercontent.com/42607534/45291172-51598100-b4e9-11e8-817c-0d276f5d082c.PNG)

**Comment by rih28** [comment]
Check with v1.7.1

**Comment by ero24** [comment]
looks great:
![img_af0e88a3758c-1](https://user-images.githubusercontent.com/42607536/45476761-bc989280-b737-11e8-83da-d172585ae439.jpeg)
