### ISSUE TITLE
q1, stats, hint 6, first little question: should be a full stop instead of a comma

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#116]
"..there are 200 people in total, If..." should be: "..there are 200 people in total. If.."
![img_0114](https://user-images.githubusercontent.com/42607536/45291463-29b6e880-b4ea-11e8-931b-bc9c293fa8b3.PNG)

**Comment by rih28** [comment]
Check with v1.7.1

**Comment by yw666666** [comment]
fixed
