### ISSUE TITLE
Q2 algebra, fourth hint, second little question, extra apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#117]
sequence 1 3 6 10
its common second difference
![img_d74e65c308b8-1](https://user-images.githubusercontent.com/42607534/45291561-74386500-b4ea-11e8-82bd-d415f757256a.jpeg)

**Comment by rih28** [comment]
Recheck in v1.7.1

**Comment by ero24** [comment]
correct now:
![img_98a9e0b83437-1](https://user-images.githubusercontent.com/42607536/45476964-48122380-b738-11e8-90c9-02932f8d7299.jpeg)
