### ISSUE TITLE
Q2 algebra, second hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#118]
after i chose "subtract 2" or "divide by 3"
we need to add 3
![img_5216](https://user-images.githubusercontent.com/42607534/45291872-3c7ded00-b4eb-11e8-8eb7-db73c338d25a.PNG)

**Comment by rih28** [comment]
Recheck in v1.7.1

**Comment by yw666666** [comment]
Sorry I meant "need to add 3" is incorrect, it should be "add 2".

**Comment by rih28** [comment]
Fixed, check in a few days in 1.8.1

**Comment by ero24** [comment]
is fine now
