### ISSUE TITLE
Q3 algebra, fifth hint, extra apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#119]
S 1 4 9 16
after i chose "triangular numbers"
its common second difference
![img_5217](https://user-images.githubusercontent.com/42607534/45292296-b2cf1f00-b4ec-11e8-81ae-ba0e02dd1580.PNG)

**Comment by rih28** [comment]
Recheck in v1.7.1

**Comment by ero24** [comment]
looks correct:
![img_444e2c709f9c-1](https://user-images.githubusercontent.com/42607536/45477290-21a0b800-b739-11e8-86c1-b75405f7987d.jpeg)
