### ISSUE TITLE
Q4 algebra, missing apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#121]
S 1 8 27 64
after i chose Fibonacci
dont have a ...
![img_5218](https://user-images.githubusercontent.com/42607534/45292438-240ed200-b4ed-11e8-8acd-4261c991e802.PNG)

**Comment by rih28** [comment]
Check later in the week in version 1.7.1

**Comment by ero24** [comment]
is cool now:
![img_02923c42078b-1](https://user-images.githubusercontent.com/42607536/45477531-9d9b0000-b739-11e8-94a2-437444de6b25.jpeg)
