### ISSUE TITLE
Q4 algebra, third hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#122]
S 1 8 27 64
after I chose add 38, 
to get from 64 to 27, should be the other way round
![img_5219](https://user-images.githubusercontent.com/42607534/45292513-5e786f00-b4ed-11e8-884e-62840311c8bd.PNG)

**Comment by rih28** [comment]
Check later in the week in build 1.7.1

**Comment by ero24** [comment]
makes a great deal more sense:
![img_f32cba6bc2d2-1](https://user-images.githubusercontent.com/42607536/45477732-19954800-b73a-11e8-9b61-f98cbe16af0f.jpeg)
