### ISSUE TITLE
Q2 number, fourth hint, ambiguous response?

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#123]
Alex and Bryan
after I chose the second or the third option, the response was "Whilst valid...", but they're not even valid for this equation. Is this a bit ambiguous?
![img_5220](https://user-images.githubusercontent.com/42607534/45293357-e1022e00-b4ef-11e8-811c-6a07d59f5cf0.PNG)
![img_5221](https://user-images.githubusercontent.com/42607534/45293362-e2cbf180-b4ef-11e8-89e7-620c229faa89.PNG)

**Comment by rih28** [comment]
Check in v1.7.1

**Comment by ero24** [comment]
looks ok now:
![img_0d016556b9c3-1](https://user-images.githubusercontent.com/42607536/45477969-c66fc500-b73a-11e8-8d12-ca2a9e3d8580.jpeg)
