### ISSUE TITLE
Q1 in ratio, third hint, extra apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#125]
two cubic boxes problem
"its area"
extra apostrophe in all the responses to the wrong answers
![41437858_290492491541798_3420389513606725632_n](https://user-images.githubusercontent.com/42607534/45301889-c76de000-b509-11e8-964b-35dcccae0ee2.png)

**Comment by rih28** [comment]
Check in v1.7.1

**Comment by yw666666** [comment]
fixed
