### ISSUE TITLE
Q1 in ratio, fifth hint, typo (extra full stop)

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#126]
two cubic boxes question
a minor typo, theres an extra full stop
![41399586_237415460264830_2128387519027347456_n](https://user-images.githubusercontent.com/42607534/45302046-36e3cf80-b50a-11e8-9dc9-fb58871a2184.jpg)

**Comment by rih28** [comment]
Check with v1.7.1

**Comment by yw666666** [comment]
fixed
