### ISSUE TITLE
Q3 ratio, third hint, missing bracket

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#127]
students score ABC question
can either write as denominator (5) , or denominator 5?
this happens for all the responses to the wrong answers
![41473058_465350483960555_6227753148144943104_n](https://user-images.githubusercontent.com/42607534/45302520-719a3780-b50b-11e8-9c39-3db913612e9d.jpg)

**Comment by rih28** [comment]
Check in v1.7.1

**Comment by yw666666** [comment]
fixed
