### ISSUE TITLE
Q5 in geometry, first hint, two correct answers

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#128]
volume of the cylinder question
In this little question, I think pi h r^2 should be a correct answer too. The order doesn't matter. But when I chose it, it is deemed wrong in the response.

![41482756_452920188551471_152754467547119616_n](https://user-images.githubusercontent.com/42607534/45306051-92ff2180-b513-11e8-90aa-c642c3aa0890.png)
![41458878_524259164701519_8692735518993022976_n](https://user-images.githubusercontent.com/42607534/45306054-94304e80-b513-11e8-8a15-ca1f2baa433d.png)

**Comment by rih28** [comment]
Can be checked now, not Q5

**Comment by ero24** [comment]
it is ok now: (was q6)
![img_282d7c76d9b7-1](https://user-images.githubusercontent.com/42607536/45368390-64e51480-b5db-11e8-92d8-e2d289a04479.jpeg)
