### ISSUE TITLE
q4, Number, first hint, first little question feedback, typo maybe

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#129]
not 100% sure, but shouldn't it be: "...so the top and bottom ARE as low as possible." instead of: "...so the top and bottom is as low as possible" last line
![img_0116](https://user-images.githubusercontent.com/42607536/45353170-140cf600-b5b2-11e8-9485-cd7592e22f00.PNG)

**Comment by rih28** [comment]
Done, check in v1.7.1

**Comment by yw666666** [comment]
fixed
