### ISSUE TITLE
Q6 number, third hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#130]
Rory has a packet of sweets 
after i chose the first or second option
"we can easier see"
![img_5240](https://user-images.githubusercontent.com/42607534/45414590-a32e1280-b673-11e8-8f84-5a0ed4c86a64.PNG)

**Comment by rih28** [comment]
Fixed, can check now.

**Comment by ero24** [comment]
yup, looks correct:
![img_4cfa3c3603f2-1 2](https://user-images.githubusercontent.com/42607536/45479211-c2917200-b73d-11e8-9ed8-ffc6be45819d.jpeg)
