### ISSUE TITLE
Q7 number, second hint, third little question, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#131]
estimate 5.94/1.97 
after i chose 4, there's a typo in "greater than than 5"
also, for both the red and green responses,  it might be less confusing to put it as "greater than or equal to 5" or just "equal to 5"

![img_5241](https://user-images.githubusercontent.com/42607534/45415175-f0f74a80-b674-11e8-8803-77c9703b2eda.PNG)
![img_5242](https://user-images.githubusercontent.com/42607534/45415183-f359a480-b674-11e8-81e9-05fab90539d0.PNG)

**Comment by rih28** [comment]
Fixed the first point. I think the second point is fair but we can chat about that later. I have fixed it.

**Comment by ero24** [comment]
it is now ok.
