### ISSUE TITLE
Heads/Tails problem in probability, (50 students sit an exam) q17, hint 5

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#133]
![e8a267d2-1901-41b0-b777-20a6c3a82bba](https://user-images.githubusercontent.com/42607536/45421934-94049000-b686-11e8-907a-060a6974a960.png)

**Comment by rih28** [comment]
Done, can check now.

**Comment by ero24** [comment]
it looks nice now
![img_5985fccbfbc8-1](https://user-images.githubusercontent.com/42607536/45479632-edc89100-b73e-11e8-8f19-331a2e3e1b7d.jpeg)
