### ISSUE TITLE
Ratio, full stop and space missing (pie question), hint5, q10

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#135]
after the "...Andrew gets 1 portion = 2 pieces" would be nice to have a full stop and a space, although on Yi's phone it looks fine because it is in a different row..

![img_0004](https://user-images.githubusercontent.com/42607536/45430520-66771100-b69d-11e8-9691-30d91ff251e2.PNG)

**Comment by rih28** [comment]
Great spot! Fixed!

**Comment by ero24** [comment]
and it looks fab now:
![img_0016](https://user-images.githubusercontent.com/42607536/45480045-f4a3d380-b73f-11e8-82ab-bd3f2a21b471.PNG)
