### ISSUE TITLE
Q12 geometry, second hint, second little question, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#136]
compound object of a cylinder and a cone problem
In the response it should be the area of a cone instead of a cylinder. This happens for all the options in this little question.
![img_5248](https://user-images.githubusercontent.com/42607534/45430945-74796180-b69e-11e8-9e3b-87968e551adb.PNG)
![img_5246](https://user-images.githubusercontent.com/42607534/45430949-76dbbb80-b69e-11e8-9c58-11668635b271.PNG)

**Comment by rih28** [comment]
Great find and done! You can check now.

**Comment by yw666666** [comment]
fixed
