### ISSUE TITLE
Q13 geometry, third hint, second little question, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#137]
trapezoidal prism question
any number over itself is 1, not 2
happens for all the options 

Also, "anything multiplied by 1 stays"..., not "stay", is it?
![img_5249](https://user-images.githubusercontent.com/42607534/45431277-3b8dbc80-b69f-11e8-8f09-0773ced15183.PNG)

**Comment by rih28** [comment]
Done, can check now!

**Comment by yw666666** [comment]
fixed
