### ISSUE TITLE
geometry, q9,  2nd hint, feedback to any answer

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#139]
(what is the height of the cuboid...)

a comma and a space might be missing after the "height = h"

![img_1c400eaa7b21-1](https://user-images.githubusercontent.com/42607536/45485313-09d42e80-b74f-11e8-97ff-2037bb4e11fe.jpeg)

**Comment by rih28** [comment]
Check now!

**Comment by ero24** [comment]
looks much better now (the rest of the q is ok as well, it didn't get messed up)
