### ISSUE TITLE
Triangular pyramid, q11 geometry, third hint, second little question 

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#140]
The response has the ‘any number over itself is equal to 2’ problem (this is a different question to the other one)
![5008b09a-1b9a-4624-ab28-3cd8b03cc17a](https://user-images.githubusercontent.com/42607536/45491633-11e99980-b762-11e8-9e7e-4bdab0185558.png)

**Comment by rih28** [comment]
Check now :)

**Comment by ero24** [comment]
looks correct now
