### ISSUE TITLE
simple interest, feedback to wrong answer too big on SE

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#145]
q6, ratio, hint1, second little question, problem only comes up when choosing the second answer (from the top) simple interest = initial investment x interest rate
![img_0021](https://user-images.githubusercontent.com/42607536/45554401-37dc7000-b82e-11e8-8dfd-ea410b09b905.PNG)

**Comment by rih28** [comment]
Done, check now. Check all variants of the answer for this one as I changed little bits of them all.

**Comment by ero24** [comment]
all of them look dashing now
