### ISSUE TITLE
Question 14 (gradient question still in algebra)

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#15]
![img_285de7c56788-1](https://user-images.githubusercontent.com/42607536/44522567-e3cae980-a6ce-11e8-9e45-3bd19cda0fb0.jpeg)

last hint, selected the correct answers but nothing happens, tried selecting other answers but they all turn red for a second then become white again so clearly, these are the correct answers but nothing seems to happen

**Comment by yw666666** [comment]
worked fine on 6s plus and SE
