### ISSUE TITLE
Question 16 algebra, typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#18]
third hint, I think it should look like " let's"  instead of "let`s"
![img_b56a3002f426-1](https://user-images.githubusercontent.com/42607536/44522891-e2e68780-a6cf-11e8-9436-2c2aefa677c2.jpeg)

**Comment by rih28** [comment]
Fixed, can check now.

**Comment by ero24** [comment]
looks great now:
![img_0078](https://user-images.githubusercontent.com/42607536/45082876-3d311080-b0f2-11e8-8356-a4253259434d.PNG)
