### ISSUE TITLE
Q14 in Number, third typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#19]
"you' just..." typo in the second hint
![img_4911](https://user-images.githubusercontent.com/42607534/44522924-07dafa80-a6d0-11e8-94b2-cbea9f268a6a.PNG)

**Comment by yw666666** [comment]
There's another typo in the second hint.
![img_4912](https://user-images.githubusercontent.com/42607534/44526710-c3099080-a6dc-11e8-9347-b480e13e2c43.PNG)

**Comment by rih28** [comment]
Fixed. Can check this now.

**Comment by yw666666** [comment]
both typos are fixed
