### ISSUE TITLE
q20 in algebra first hint, typo/error

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#20]
second little question of the first hint, when I choose the answer (that is wrong) there is a typo/error in the text that comes up in the red box. This is an issue with all three wrong answers, as the feedback (the red box that comes up) has an error in response to all three of them
![img_baf8106fa1d2-1](https://user-images.githubusercontent.com/42607536/44526599-6c03bb80-a6dc-11e8-8040-7d29e2391f2b.jpeg)

**Comment by rih28** [comment]
Fixed, can check tomorrow.

**Comment by ero24** [comment]
looks ok now:
![img_0089](https://user-images.githubusercontent.com/42607536/45086013-1a0a5f00-b0fa-11e8-86f9-43d769736659.PNG)
