### ISSUE TITLE
Question 3 of ratio, typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#22]
Hint 4 in the second little question, the response for the wrong answer there is a missing closing bracket.
![img_8892](https://user-images.githubusercontent.com/42607536/44527567-24326380-a6df-11e8-88ae-3cdecb74c424.PNG)

**Comment by rih28** [comment]
This isn't question 3, but it is done and changed and can be tested tomorrow.

**Comment by yw666666** [comment]
fixed
