### ISSUE TITLE
Question 3 in ratios, typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#24]
last hint has a typo in the response to the little question (missing apostrophe)
![img_8894](https://user-images.githubusercontent.com/42607536/44528659-03b7d880-a6e2-11e8-8235-544c1286ce29.PNG)

**Comment by yw666666** [comment]
Similar typos in the same question.
![img_4991](https://user-images.githubusercontent.com/42607534/44728571-c33acf00-aad4-11e8-912e-a8e25fcc19b2.PNG)
![img_4989](https://user-images.githubusercontent.com/42607534/44728577-c635bf80-aad4-11e8-8020-56a1941125a5.PNG)
![img_4992](https://user-images.githubusercontent.com/42607534/44728578-c7ff8300-aad4-11e8-9f9d-45cbd030ac23.PNG)

**Comment by rih28** [comment]
This is not question 6. Updated, but will only be available on Friday but most likely Monday. Check then.

**Comment by yw666666** [comment]
fixed
