### ISSUE TITLE
Question 13, probability, typo?

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#34]
first little question in hint no6 the response to the answer has a missing bold "one" 
![img_8899](https://user-images.githubusercontent.com/42607536/44581063-3c17ef00-a794-11e8-8981-5f437cdc1b33.PNG)
"since there is a total of **ONE** digit"

**Comment by rih28** [comment]
I have fixed this. Can probably check now.

**Comment by yw666666** [comment]
fixed
