### ISSUE TITLE
Buttons became blue and nothing appeared when I chose the wrong option

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#35]
This is a general problem but I made screenshots of two questions as examples. This doesn't occur all the time so it might work fine when you go and re-try these questions. But this has happened a few times, making it a problem that shouldn't be ignored.

The problem is when I clicked on the wrong option in the little question, the button became blue and nothing appeared, making it look like it's a correct option. Only after I clicked again I could see the red text box. (I forgot if the option turned red too) 

Two of the examples are 
Stats Q9, "A factory has 80 pieces of rope...", fourth hint

![img_4935](https://user-images.githubusercontent.com/42607534/44581737-d416d800-a796-11e8-9ead-80f2f94a0eb2.PNG)

Stats Q13, "A box contains...", third hint

![img_4938](https://user-images.githubusercontent.com/42607534/44581728-c7927f80-a796-11e8-91e7-01862a00f595.PNG)

**Comment by yw666666** [comment]
Actually, sometimes after i chose the correct option in the little question, the green text box also didn't appear unless I clicked again.

**Comment by rih28** [comment]
Fixed, check this week.

**Comment by yw666666** [comment]
fixed
