### ISSUE TITLE
Images too large

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#36]
For all 3 of the questions, the images in the answer are too large.
Stats Q11, "Below is the cumulative frequency..." 
![img_4936](https://user-images.githubusercontent.com/42607534/44581817-31128e00-a797-11e8-9c9b-e8e1f0606405.PNG)

Stats Q13, "A box contains..."
![img_4937](https://user-images.githubusercontent.com/42607534/44581831-37086f00-a797-11e8-839e-8df6e0c3ac7c.PNG)

Stats Q15 “Students in a class…”
![img_4939](https://user-images.githubusercontent.com/42607534/44585611-d8e28880-a7a4-11e8-9105-98ed58e2d634.PNG)

**Comment by rih28** [comment]
Solved
