### ISSUE TITLE
Number Q3, hint 1, first little question, typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#38]
the response to only one of the wrong answers has a typo, 
the two should be part of the power the number is raised to
![img_c094f34759e0-1](https://user-images.githubusercontent.com/42607536/44718610-7fd26780-aab8-11e8-88e3-43e355f0f6c7.jpeg)

**Comment by rih28** [comment]
This is not question number 6 in number it is question 3. Cant check until Friday or next week more likely.

**Comment by yw666666** [comment]
fixed
![img_0bf23e386d6b-1](https://user-images.githubusercontent.com/42607534/45146802-76818300-b1bb-11e8-9c6d-c72fc8d93508.jpeg)
