### ISSUE TITLE
Buttons disappearing

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#4]
I was doing a question earlier in the Statistics section and because I tried out all the hints as well it ended up being very long with all the additional lines. When I finally clicked on the answer and got the Taj Mahal picture I could scroll in the background and the two buttons (continue and find out more) disappeared. (then I just tapped somewhere random and that took me to the next question)

**Comment by rih28** [comment]
Which question?

**Comment by ero24** [comment]
it was question 4, the pie chart question

**Comment by ero24** [comment]
happened again with question 9 as well, in the same section (Algebra)
