### ISSUE TITLE
Q7 in Ratio

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#41]
Q7 in ratio, second hint, after choosing "1.2 tourists" this appeared
![img_4993](https://user-images.githubusercontent.com/42607534/44728914-7efbfe80-aad5-11e8-8408-c12cb98c59f1.PNG)

**Comment by rih28** [comment]
Updated, can check now.

**Comment by ero24** [comment]
looks much less confusing:
![img_0080 copy](https://user-images.githubusercontent.com/42607536/45083152-ec6de780-b0f2-11e8-9c09-3aff779141e1.PNG)
