### ISSUE TITLE
Problem specific hint

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#5]
For some of the questions (eg the HCF question in Number), when I clicked on the last hint, its content is specific to the questions and has already completed the question halfway for the user. Before I clicked on the link, I had no idea that this hint is problem-specific. Maybe some students would prefer to solve the question by themselves after reading the general hints. I think it's better to allow students to choose if they want to try the question on their own or look at the "ultimate"&problem-specific hint (just like the different types of hints on the "I want to study engineering" website.) But not all the questions have this problem and some of them do need a specific hint to teach the students. Thus it might a bit tedious to adjust the hints to solve this issue.

**Comment by rih28** [comment]
I think we should leave this just now.
