### ISSUE TITLE
Install; Switch off network before app starts; try some questions; then put network on.

### ISSUE THREAD

**Issue by rih28** [rih28/MBTest#51]

**Comment by ero24** [comment]
I switched network back before completing the 5th question and as I pressed continue after I got the answer right, the app went to the home page instead of the next question then it updated and displayed the 4/20 correctly.

**Comment by yw666666** [comment]
I switched off network before the app started, tried 3 questions and switched network on and continued. When I finished the sixth question(I don't remember exactly but I think it is), the app crashed and exited. I tried to open it but it exited again. After I reinstalled the app and repeated what I did, everything seemed fine. Perhaps it's a one-time thing

**Comment by rih28** [comment]
Interesting, I will look into it.
