### ISSUE TITLE
Q12 in algebra, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#52]
ninth hint, involves an "or equal to"
![img_0003](https://user-images.githubusercontent.com/42607534/44862076-dcc54d80-ac71-11e8-8a54-ca7311dc85aa.PNG)

**Comment by rih28** [comment]
Ask me about this tomorrow!

**Comment by rih28** [comment]
Think I have fixed, can check now, but only one apos will be shown at the moment so will have to stay open.

**Comment by yw666666** [comment]
The apos are fixed for the ninth and tenth hint now. 
Do you think we should remove the comma after "an"?
![img_5087](https://user-images.githubusercontent.com/42607534/45146563-0ecb3800-b1bb-11e8-970c-c7a073477506.PNG)
![img_5088](https://user-images.githubusercontent.com/42607534/45146564-112d9200-b1bb-11e8-8f4d-cfcab4d50c81.PNG)

**Comment by rih28** [comment]
Nah, this is fine :).
