### ISSUE TITLE
SE Q6 in Algebra, couldn't open the summary for the first hint

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#53]
Q6 in algebra, "solve the equation 3x-4=11-2x "
The screen could display up to 4 hint buttons and after I finished the fifth hint, I couldn't swipe left to go back to the first hint to open the summary
![img_4752290a94af-1](https://user-images.githubusercontent.com/42607534/44862422-8d335180-ac72-11e8-8a92-36e7c661d1a6.jpeg)

**Comment by rih28** [comment]
On what device?

**Comment by yw666666** [comment]
It's on iphone SE

**Comment by rih28** [comment]
Fixed this, check this week.

**Comment by ero24** [comment]
works fine on SE now.
