### ISSUE TITLE
SE Hint summary too long

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#54]
In both of the questions, the summary was too long and I couldn't scroll down
Q16 in algebra, “simplify fully d^5/d^3”
first hint:

![img_0004](https://user-images.githubusercontent.com/42607534/44862612-f915ba00-ac72-11e8-9cf8-b51e9f52cb8b.PNG)

**Comment by yw666666** [comment]
Q16 in algebra, “simplify fully d^5/d^3”
second hint:
![img_0005](https://user-images.githubusercontent.com/42607534/44862764-4db93500-ac73-11e8-8d0e-fd9f629441cb.PNG)

**Comment by yw666666** [comment]
Q19 in algebra “simplify full a^5…”, fifth hint

![img_0007](https://user-images.githubusercontent.com/42607534/44862571-dd121880-ac72-11e8-8659-4ed526c0535a.PNG)

**Comment by yw666666** [comment]
Q8, fourth hint in Number
![img_0017](https://user-images.githubusercontent.com/42607534/44909364-f40a4680-ad16-11e8-8de3-d88b0f5091c0.PNG)

**Comment by yw666666** [comment]
Q10 first hint in Number
![img_0018](https://user-images.githubusercontent.com/42607534/44909487-74c94280-ad17-11e8-9f4e-5a0aaa194ba5.PNG)

**Comment by yw666666** [comment]
Q11 first hint, Number
![img_0020](https://user-images.githubusercontent.com/42607534/44915278-7fd99e00-ad2a-11e8-98e2-24bdd2b89868.PNG)

**Comment by yw666666** [comment]
Q18, first hint, Number
![img_0021](https://user-images.githubusercontent.com/42607534/44915327-9aac1280-ad2a-11e8-805d-83999271ac83.PNG)

**Comment by yw666666** [comment]
Q19, first hint, Number
![img_0022](https://user-images.githubusercontent.com/42607534/44915352-abf51f00-ad2a-11e8-8736-497be4e50e7a.PNG)

**Comment by yw666666** [comment]
Q7 Probability, third hint
![img_0026](https://user-images.githubusercontent.com/42607534/44918048-f201b100-ad31-11e8-9821-ca49fe969699.PNG)

**Comment by yw666666** [comment]
Q10, Probability, first hint
![img_f2ce177bc15c-1](https://user-images.githubusercontent.com/42607534/44918393-b3b8c180-ad32-11e8-99c0-f7be4a91bf8f.jpeg)

**Comment by yw666666** [comment]
Q12 Probability, third hint
![img_0030](https://user-images.githubusercontent.com/42607534/44918736-9fc18f80-ad33-11e8-8367-41d94ebff696.PNG)

**Comment by yw666666** [comment]
Q15 Probability fourth hint
![img_0033](https://user-images.githubusercontent.com/42607534/44919402-5a9e5d00-ad35-11e8-83e9-04cf12445797.PNG)

**Comment by yw666666** [comment]
Q17, Probability, first hint
![img_0042](https://user-images.githubusercontent.com/42607534/44919950-9f76c380-ad36-11e8-9382-64dafa49174d.PNG)

**Comment by yw666666** [comment]
Q19, Probability, third hint
![img_0046](https://user-images.githubusercontent.com/42607534/44920161-1744ee00-ad37-11e8-8c80-3624110b9cc9.PNG)

**Comment by yw666666** [comment]
Q20, Probability, fourth hint
![img_0047](https://user-images.githubusercontent.com/42607534/44920383-aeaa4100-ad37-11e8-83e6-8f5454f6aa19.PNG)

**Comment by rih28** [comment]
As a point, these should be separate as they will be hard to close without doing all of them first and this is where mistakes are made.

**Comment by rih28** [comment]
I think these are all fixed now

**Comment by ero24** [comment]
some of them are fine now but not all, I put the not fine ones in separate issues
