### ISSUE TITLE
Summary text remains after I clicked on redo button

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#55]
when i clicked on the redo button without closing the summary text for the blue hints, the summary text remains, which seems a bit weird.

(Q16 “simplify fully d^5/d^3” in algebra) Notice that the redo button has been clicked.

![img_0006](https://user-images.githubusercontent.com/42607534/44863134-33cc2200-ac74-11e8-934b-a2d8221caeb6.PNG)

**Comment by yw666666** [comment]
This happened on both iphone SE and iphone 6S. Also it happened on other questions, the above question is just an example.

**Comment by rih28** [comment]
This has been fixed. Check next week.

**Comment by yw666666** [comment]
fixed
