### ISSUE TITLE
Statistics, question1, hint8

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#56]
the last line of the lesson doesn't have any explanation, also there is no question, it looks like some text is missing from the last line
![img_0009](https://user-images.githubusercontent.com/42607536/44903404-5d348e80-ad04-11e8-9c01-b9b9346d8a0f.PNG)

**Comment by rih28** [comment]
Fixed this, check next week

**Comment by ero24** [comment]
works fine now.
