### ISSUE TITLE
Question 9, first hint, little question 5, text too big (statistics)

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#58]
text seems to be a bit too big for the SE screen 
![img_267d68f04204-1](https://user-images.githubusercontent.com/42607536/44904968-9111b300-ad08-11e8-84cb-dfa2cb33aecc.jpeg)

**Comment by rih28** [comment]
Fixed, can check now.

**Comment by ero24** [comment]
it was q11 and it is fine now:
![img_0053](https://user-images.githubusercontent.com/42607536/45021368-486c3980-b029-11e8-89cf-343e8a29183f.PNG)
