### ISSUE TITLE
SE Q1 in Number, first hint, button a bit too small

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#59]
The small button beside "multiplication" is quite small but still works. It might cause a problem for a phone with a slightly smaller screen?
![img_0012](https://user-images.githubusercontent.com/42607534/44908254-b4d9f680-ad12-11e8-8b57-8de5553aa790.PNG)

**Comment by rih28** [comment]
fixed, check next week

**Comment by ero24** [comment]
works fine now.
![img_0051](https://user-images.githubusercontent.com/42607536/44990037-b8c27e80-af87-11e8-8397-058704d7c065.PNG)
