### ISSUE TITLE
Q3 & Q5 in Number, text incorrectly displayed from time to time

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#60]
Q3 in Number, second hint
Q5 in Number, second hint
The incorrect text appeared (which I think has been fixed?), but when I tried the questions again, it was correctly displayed. When I tried again, it was again incorrectly displayed. This happened on SE. When I tried it several times on my phone, it was always incorrectly displayed.
Q5:
![img_2672580fe52a-1](https://user-images.githubusercontent.com/42607534/44908741-8f4dec80-ad14-11e8-9946-e71cf4d85e54.jpeg)
![img_0015](https://user-images.githubusercontent.com/42607534/44908744-91b04680-ad14-11e8-9a2d-66389353e063.PNG)

Q3:
![img_0014](https://user-images.githubusercontent.com/42607534/44908756-a1c82600-ad14-11e8-8120-c733fee7866c.PNG)

**Comment by rih28** [comment]
Done, check next week.

**Comment by yw666666** [comment]
It worked fine on both questions on 6s plus and SE.
