### ISSUE TITLE
Q5 and Q6 in Number have the same museum

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#61]
Both questions have the same museum - technical museum of Vienna
happened both on my phone and SE
![img_5034](https://user-images.githubusercontent.com/42607534/44908924-48142b80-ad15-11e8-8147-c44b5b1cd0d9.PNG)

**Comment by rih28** [comment]
This doesnt happen on mine.

**Comment by rih28** [comment]
I just tested this on the emulator and my phone and it worked perfectly. I think we need to try this again.

**Comment by yw666666** [comment]
fixed now
