### ISSUE TITLE
SE Q7 Probability third hint, text didn't fit into the red box

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#65]
"Phil tosses a coin twice" third hint

![img_0025](https://user-images.githubusercontent.com/42607534/44917749-2b85ec80-ad31-11e8-9ac6-e1b3903e31bd.PNG)

**Comment by ero24** [comment]
it looks nice now:
![img_0075](https://user-images.githubusercontent.com/42607536/45082520-6a30f380-b0f1-11e8-9f9f-c37b80977b80.PNG)
