### ISSUE TITLE
Q12 Probability, fourth hint, text in the little question doesn't fit on SE

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#66]
Q12 Probability, fourth hint
![img_0029](https://user-images.githubusercontent.com/42607534/44918677-7d2f7680-ad33-11e8-975f-b8b1fb7d83f5.PNG)

**Comment by yw666666** [comment]
same question, same hint

![img_0031](https://user-images.githubusercontent.com/42607534/44918850-e4e5c180-ad33-11e8-9974-bc193023e847.PNG)

**Comment by yw666666** [comment]
Q15, fifth hint
![img_0032](https://user-images.githubusercontent.com/42607534/44919371-422e4280-ad35-11e8-85b7-592560640376.PNG)

**Comment by rih28** [comment]
We need to make these separate.

**Comment by rih28** [comment]
I think this is complete. Probably check now.

**Comment by ero24** [comment]
it is looking fab now:
![img_0055](https://user-images.githubusercontent.com/42607536/45021681-1ad3c000-b02a-11e8-8725-9cac540ccd3f.PNG)
