### ISSUE TITLE
Q12 Probability, fourth hint, text in the little question doesn't fit on SE

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#68]
![img_0031](https://user-images.githubusercontent.com/42607534/44918850-e4e5c180-ad33-11e8-9974-bc193023e847.PNG)

**Comment by rih28** [comment]
Can check now :)

**Comment by ero24** [comment]
looks cool now:
![img_0073](https://user-images.githubusercontent.com/42607536/45082180-a9127980-b0f0-11e8-89f8-9f4f49f9f82f.PNG)
