### ISSUE TITLE
Q15, Probability, fifth hint, text in the little question doesn't fit on SE

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#69]
![img_0032](https://user-images.githubusercontent.com/42607534/44919371-422e4280-ad35-11e8-85b7-592560640376.PNG)

**Comment by rih28** [comment]
Can check now :)

**Comment by ero24** [comment]
it is fine now, as seen below
![img_0052](https://user-images.githubusercontent.com/42607536/45021113-a51b2480-b028-11e8-98b8-e04611391ce7.PNG)
