### ISSUE TITLE
Qn1 in Number

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#7]
For the first little question in Qn1 in Number, I was asked to select the operations in the order we do them in. Some of the operations are interchangeable, but the students weren't told this (they were only told after they passed the hint) so it's a bit confusing. Maybe it's better to put the interchangeable ones together (eg multiplication&division), or tell them about this before they start doing it?

**Comment by rih28** [comment]
BIDMAS or BODMAS is outlined in the GCSE syllabus so it is perhaps best not to muddy waters at this stage.
