### ISSUE TITLE
Question 3 ratio, hint5 wrong answer and typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#70]
there is an extra zero on the thousand (it should only be a hundred)
![img_8893](https://user-images.githubusercontent.com/42607536/44527747-a884e680-a6df-11e8-9b63-fdb29dabc2eb.PNG)

also the  feedback to the answer is completely wrong, as the one I clicked is the correct answer actually and it says it is wrong

**Comment by rih28** [comment]
What question is this?

**Comment by rih28** [comment]
I don't think this is Ratio q3!

**Comment by rih28** [comment]
This is fixed and could probably be checked now!

**Comment by ero24** [comment]
it was q11, and it's fine now.
