### ISSUE TITLE
Q18, geometry, third hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#72]
"what is the area of the curved face..."
![img_4926](https://user-images.githubusercontent.com/42607534/44537164-045a6a00-a6f6-11e8-9a7e-89c2046c55d9.PNG)

**Comment by rih28** [comment]
fixed, check later in the week :)

**Comment by ero24** [comment]
looks flawless now:
![img_0079](https://user-images.githubusercontent.com/42607536/45083004-8ed99b00-b0f2-11e8-86e7-9bda52ed3768.PNG)
