### ISSUE TITLE
Q18, geometry, apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#73]
first hint, missing apostrophe
![img_5060](https://user-images.githubusercontent.com/42607534/44990349-a72da680-af88-11e8-8477-7e4a793a3d7b.PNG)

**Comment by rih28** [comment]
Fixed, check later in the week :).

**Comment by ero24** [comment]
looks amazing now: (text is also easier to read)
![img_0076 copy](https://user-images.githubusercontent.com/42607536/45082695-cbf15d80-b0f1-11e8-90ec-1a2e33488aeb.PNG)
