### ISSUE TITLE
Q20, Probability, fourth hint, summary text too large

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#74]
![img_0047](https://user-images.githubusercontent.com/42607534/44920383-aeaa4100-ad37-11e8-83e6-8f5454f6aa19.PNG)

**Comment by rih28** [comment]
fixed. check later this week.

**Comment by ero24** [comment]
absolutely fabulous:
![img_0072](https://user-images.githubusercontent.com/42607536/45081988-43be8880-b0f0-11e8-96fd-161506ca6e72.PNG)
