### ISSUE TITLE
Q19, Probability, third hint, summary text too large

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#75]
![img_0046](https://user-images.githubusercontent.com/42607534/44920161-1744ee00-ad37-11e8-8c80-3624110b9cc9.PNG)

**Comment by rih28** [comment]
Fixed, check this week.

**Comment by ero24** [comment]
looks amazing now:
![img_0071](https://user-images.githubusercontent.com/42607536/45081764-d27ed580-b0ef-11e8-9ef9-b107aa2c0e02.PNG)
