### ISSUE TITLE
Q7 Probability, third hint, summary text too large

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#76]
![img_0026](https://user-images.githubusercontent.com/42607534/44918048-f201b100-ad31-11e8-9821-ca49fe969699.PNG)

**Comment by rih28** [comment]
Fixed, check next week.

**Comment by ero24** [comment]
looks great now:
![img_0070 copy](https://user-images.githubusercontent.com/42607536/45081556-5c7a6e80-b0ef-11e8-97d0-8a3094ceb9b6.PNG)
