### ISSUE TITLE
Question 2 missing apostrophe (Algebra section)

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#8]
First little question (and then successive little questions as well): after selecting the correct answer the green box says; 'Well done! Thats correct!' instead of That's correct ie; apostrophe is missing

**Comment by rih28** [comment]
Check every one of the questions, especially for <apos> as I have done a blanket change! Only in the first 5 of every topic. Be thorough!

**Comment by yw666666** [comment]
The apostrophe worked. (first hint & fourth hint in this question)
