### ISSUE TITLE
Q8, fourth hint in Number, summary text too large

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#81]
![img_0017](https://user-images.githubusercontent.com/42607534/44909364-f40a4680-ad16-11e8-8de3-d88b0f5091c0.PNG)

**Comment by rih28** [comment]
This has been resolved, test in a few days

**Comment by ero24** [comment]
This works fine now:

![img_0066 copy](https://user-images.githubusercontent.com/42607536/45080924-e9bcc380-b0ed-11e8-9127-7bcdc13e71b7.PNG)
