### ISSUE TITLE
Q16 in algebra, “simplify fully d^5/d^3” second hint, summary too large

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#82]
![img_0005](https://user-images.githubusercontent.com/42607534/44862764-4db93500-ac73-11e8-8d0e-fd9f629441cb.PNG)

**Comment by rih28** [comment]
This is resolved. Test in a few days!

**Comment by ero24** [comment]
this looks fine now:
![img_0064](https://user-images.githubusercontent.com/42607536/45080392-ba598700-b0ec-11e8-9634-d161173bdb6a.PNG)
