### ISSUE TITLE
Q12 in algebra, tenth hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#83]
to represent a "less than" inequality
![img_bbfc50b73ece-1](https://user-images.githubusercontent.com/42607534/44995155-a4877d00-af99-11e8-8218-daac3bc686b9.jpeg)

**Comment by rih28** [comment]
I will keep this one open just now given the issues with apple and the apostrophes (and quotations)

**Comment by ero24** [comment]
found a correctly working set of quotation marks in the Algebra, Q1, first hint, response to any wrong answer:
![img_0056](https://user-images.githubusercontent.com/42607536/45021986-f5938180-b02a-11e8-887e-606a208ba6d5.PNG)

**Comment by rih28** [comment]
Okay, but it needs to be in the summary i.e. when you click on a blue button. part not in the feedback in a lesson.

**Comment by rih28** [comment]
I have fixed, can check now, but only one apos will show so will need to stay open.

**Comment by rih28** [comment]
With 1.4.1 (out today)  this should work perfectly.

**Comment by ero24** [comment]
it does work perfectly:
![img_0074](https://user-images.githubusercontent.com/42607536/45082333-09a1b680-b0f1-11e8-9257-14e4eaf31a06.PNG)
