### ISSUE TITLE
Question 6, Algebra, summary is the same for hint1 and hint5

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#84]
When I click on either blue hint buttons, the same hint comes up, we found that this only happens if you choose the -3x option at first (in the second hint)
![img_0059](https://user-images.githubusercontent.com/42607536/45027361-1531a680-b039-11e8-870f-d7678381fae5.PNG)

**Comment by rih28** [comment]
I think I have fixed this. This will need a lot of checking of other questions and pressing Next Q and Last Q a lot, just to make sure! This will not be available until probably next week, Friday at best!

**Comment by ero24** [comment]
this works fine now, different summaries for the different hints come up
