### ISSUE TITLE
First question, third hint, Geometry, feedback to correct answer typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#85]
into appears twice
![img_0061](https://user-images.githubusercontent.com/42607536/45028227-229c6000-b03c-11e8-8561-e68bda16be5a.PNG)

**Comment by rih28** [comment]
Fixed, will have to wait until either Friday but most likely next week to test.

**Comment by ero24** [comment]
it is fine now:
![img_0096](https://user-images.githubusercontent.com/42607536/45145967-c8c1a480-b1b9-11e8-941f-6956804d205d.PNG)
