### ISSUE TITLE
q6, summary of the second hint, Statistics, typo

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#86]
there is an extra <br> there
![img_0062](https://user-images.githubusercontent.com/42607536/45034890-95173b00-b050-11e8-9a55-38c3b6e92e85.PNG)

**Comment by rih28** [comment]
I don't understand your comment. I guess its the <br>

**Comment by rih28** [comment]
Fixed. Can probably check now.

**Comment by ero24** [comment]
I meant the break, but when I typed it, I think it interpreted it as a command, anyway this looks fine now:
![img_0065](https://user-images.githubusercontent.com/42607536/45080745-7f0b8800-b0ed-11e8-9561-051d3ac32881.PNG)
