### ISSUE TITLE
q10 Statistics, second hint, second little question, text too big

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#87]
text seems to be just slightly too big for the screen of the SE 
![img_0063](https://user-images.githubusercontent.com/42607536/45040195-59cf3900-b05d-11e8-8ae1-10a3503cf9af.PNG)

**Comment by ero24** [comment]
the screenshot doesn't show it properly but it looks like this:
![img_5071](https://user-images.githubusercontent.com/42607536/45040300-99962080-b05d-11e8-90a9-2d0e8a70eba4.JPG)
![img_5072](https://user-images.githubusercontent.com/42607536/45040302-9a2eb700-b05d-11e8-99b8-e556af1d7311.JPG)

**Comment by rih28** [comment]
Fixed. Can check now.

**Comment by ero24** [comment]
it is fine now
