### ISSUE TITLE
Missing apostrophe in question 6 - x(x+3)  (algebra)

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#9]
In little question 4, after picking an answer the explanation comes up and says "dont" instead of "don't". Then when I tap on hint 4 in the question and the little help text comes up it is wrong there as well (same text) "we dont need to put the times sign in"

**Comment by ero24** [comment]
re-check in a couple of days

**Comment by rih28** [comment]
Fixed, can be checked now. May have issues with multiple <apos>

**Comment by yw666666** [comment]
The apostrophe worked fine in the explanation and the hint summary in this question.
