### ISSUE TITLE
Q7, algebra, extra apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#90]
Q6 in algebra, "What is the correct expansion of the expression x(x+3)?"
hint 1, after choosing "solving to find the unknown blah" there's an extra apostrophe in the red box - on its own
![img_5079](https://user-images.githubusercontent.com/42607534/45082797-0eb33580-b0f2-11e8-91f1-09a245efedc8.PNG)

**Comment by rih28** [comment]
In the image above?

**Comment by yw666666** [comment]
yes in the image it says on it's own

**Comment by yw666666** [comment]
fixed
