### ISSUE TITLE
Q20, Number, third hint, answer buttons too small (two number machines q)

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#92]
in the second hint as well, the sizes of the answer buttons are barely large enough, however in the third hint, they are obviously too small:
![img_0091](https://user-images.githubusercontent.com/42607536/45102457-b4cc6300-b125-11e8-8d2a-8d1b68154e0d.PNG)

**Comment by rih28** [comment]
Fixed, can check now!

**Comment by rih28** [comment]
You will need to delete the app remember.

**Comment by ero24** [comment]
looks great now: (and all the other hints as well)
![img_0093](https://user-images.githubusercontent.com/42607536/45105141-8782b380-b12b-11e8-8567-e01e6e0256b6.PNG)
