### ISSUE TITLE
Q4 in probability, sixth hint, typo

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#93]
Q4 in probablity, "Jane has a basket blah blah", sixth hint
I suppose the last or second last scenario should be "tails and heads"?
By the way why do we have two different colours for heads and tails?
![img_5082](https://user-images.githubusercontent.com/42607534/45102381-8189d400-b125-11e8-9e6f-7aae7c1ccf49.PNG)

**Comment by rih28** [comment]
Fixed, will need to wait until next week to test.

**Comment by rih28** [comment]
This is not in stats!

**Comment by yw666666** [comment]
sorry, it's in probability.

**Comment by rih28** [comment]
Its ok :)

**Comment by ero24** [comment]
same problem appears in q3, hint3, little question 2

**Comment by ero24** [comment]
fixed in both questions.
