### ISSUE TITLE
typo in q21, number (sam's catching a train..), summary of the first hint

### ISSUE THREAD

**Issue by ero24** [rih28/MBTest#94]
"written int he format" also, there is no full stop at the end so maybe the summary doesn't fit?
![img_0092](https://user-images.githubusercontent.com/42607536/45103518-f78f3a80-b127-11e8-92d0-dc5ad4ceeee0.PNG)

**Comment by rih28** [comment]
Done, you can check it now!

**Comment by ero24** [comment]
typo is corrected but it looks a bit weird now:
![img_0094](https://user-images.githubusercontent.com/42607536/45105482-3e7f2f00-b12c-11e8-8485-b79f5ea2f088.PNG)

**Comment by rih28** [comment]
Is it better now? I changed it again?

**Comment by ero24** [comment]
I think it looks alright now:
![img_0095](https://user-images.githubusercontent.com/42607536/45145810-77191a00-b1b9-11e8-89d9-be607b4d41c5.PNG)
