### ISSUE TITLE
Q4, first hint, Number, extra apostrophe

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#97]
Q4 "express 3/12 as a percentage"
A fraction is in its simplest form...

![img_5090](https://user-images.githubusercontent.com/42607534/45150747-805bb400-b1c4-11e8-9ef5-d254ad96d75d.PNG)

**Comment by rih28** [comment]
Check in a few days.

**Comment by ero24** [comment]
same issue with first hint, second little question
![img_0117](https://user-images.githubusercontent.com/42607536/45353394-9ac1d300-b5b2-11e8-8d53-efae3b5a1f34.PNG)

**Comment by yw666666** [comment]
fixed in both little questions
