### ISSUE TITLE
Q4, first hint, Number, extra apostrophe again

### ISSUE THREAD

**Issue by yw666666** [rih28/MBTest#98]
Q4 "express 3/12 as a percentage"
expressed in its simplest terms
![img_caa158b3709f-1](https://user-images.githubusercontent.com/42607534/45150893-cdd82100-b1c4-11e8-94e2-ec922102d486.jpeg)

**Comment by rih28** [comment]
Check in a few days.

**Comment by yw666666** [comment]
fixed
